# Generated by Django 2.0.4 on 2018-04-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('link', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
