# Generated by Django 2.0.4 on 2018-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180410_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ints1', models.CharField(default='', max_length=250)),
                ('ints2', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=250)),
                ('LastName', models.CharField(default='', max_length=250)),
                ('Email', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
