# Generated by Django 2.0.4 on 2018-04-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_ints_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rest.Ints'),
        ),
    ]
